# Generated by Django 4.2.1 on 2023-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=200)),
                ('no_of_flats', models.PositiveIntegerField()),
                ('builder', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('constructed_on', models.DateField()),
                ('maintenance_rating', models.IntegerField()),
            ],
        ),
    ]
